name: cling
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  bloc: ^8.1.2
  build_runner: ^2.4.6
  dropdown_button2: ^2.3.6
  email_validator: ^2.1.17
  equatable: ^2.0.5
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_expandable_fab: ^1.8.1
  flutter_gen: ^5.3.1
  flutter_native_splash: ^2.3.1
  flutter_svg: ^2.0.7
  get_it: ^7.6.0
  lottie: ^2.5.0
  neon_widgets: ^2.0.0
  open_mail_app: ^0.4.5
  rename: ^2.1.1
  shared_preferences: ^2.2.0
  sizer: ^2.0.15
  sqflite: ^2.3.0
  syncfusion_flutter_charts: ^22.1.39
  transitioned_indexed_stack: ^1.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/resources/images/logo_png.png"

flutter:
  uses-material-design: true
  assets:
    - lib/resources/images/
    - lib/resources/anim/
  fonts:
    - family: Bungee
      fonts:
        - asset: lib/resources/fonts/Bungee-Regular.ttf
    - family: Cabinet Grotesk
      fonts:
        - asset: lib/resources/fonts/CabinetGrotesk-Bold.otf
        - asset: lib/resources/fonts/CabinetGrotesk-Regular.otf

flutter_gen:
  output: lib/resources/gen/ # Optional (default: lib/gen/)

  # Optional
  integrations:
    flutter_svg: true
