name: cling
description: A Money Management App.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  bloc: ^8.1.2
  connectivity_plus: ^4.0.2
  dropdown_button2: ^2.3.6
  email_validator: ^2.1.17
  equatable: ^2.0.5
  firebase_analytics: ^10.4.4
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_expandable_fab: ^1.8.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  get_it: ^7.6.0
  intl: ^0.18.0
  lottie: ^2.5.0
  modal_bottom_sheet: ^3.0.0-pre
  money_formatter: ^0.0.4
  nil: ^1.1.1
  open_mail_app: ^0.4.5
  rename: ^2.1.1
  shared_preferences: ^2.2.0
  sizer: ^2.0.15
  sqflite: ^2.3.0
  syncfusion_flutter_charts: ^22.1.39
  transitioned_indexed_stack: ^1.0.2

dev_dependencies:
  arb_generator: ^0.0.3
  # flutter_gen: ^5.3.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/resources/images/logo_png.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/resources/images/
    - lib/resources/anim/
  fonts:
    - family: Bungee
      fonts:
        - asset: lib/resources/fonts/Bungee-Regular.ttf
    - family: Cabinet Grotesk
      fonts:
        - asset: lib/resources/fonts/CabinetGrotesk-Bold.otf
        - asset: lib/resources/fonts/CabinetGrotesk-Regular.otf

arb_generator:
  input_filepath: "lib/resources/localization/localization_cling.csv"
  output_directory: "lib/l10n"
  filename_prepend: "app_"
  csv_settings:
    delimiter: ","
    description_index: null
    base_index: 2

flutter_gen:
  output: lib/resources/gen/ 
  integrations:
    flutter_svg: true
