// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmX_mcUR0h1fNv6Kk0iy9UhS5G2EKuOb8',
    appId: '1:726454501636:web:6e123c0a8b2355ec6d1051',
    messagingSenderId: '726454501636',
    projectId: 'cling-c49aa',
    authDomain: 'cling-c49aa.firebaseapp.com',
    storageBucket: 'cling-c49aa.appspot.com',
    measurementId: 'G-B8JRCMWNR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl7wqJThd-_E68DSKI53ECk7x3YGCgWI0',
    appId: '1:726454501636:android:ab702bbb891ffed96d1051',
    messagingSenderId: '726454501636',
    projectId: 'cling-c49aa',
    storageBucket: 'cling-c49aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS3yxM9-35Krz_e8yyY325UqX7fmzIaRU',
    appId: '1:726454501636:ios:c3634a1b70470c606d1051',
    messagingSenderId: '726454501636',
    projectId: 'cling-c49aa',
    storageBucket: 'cling-c49aa.appspot.com',
    iosClientId: '726454501636-6gfr5fknobmh0do3tga12aps810cb947.apps.googleusercontent.com',
    iosBundleId: 'com.maul.cling',
  );
}
